### ISSUE TITLE
Trying to load client files on server

### ISSUE THREAD

**Issue by KuroNeko87** [VanyaBaou/SpartanWeaponryArcana#1]
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.vanyabaou.spartanweaponryarcana.util.StringHelper.translateString(StringHelper.java:35) ~[StringHelper.class:?]
	at com.vanyabaou.spartanweaponryarcana.util.StringHelper.translateString(StringHelper.java:25) ~[StringHelper.class:?]
	at com.vanyabaou.spartanweaponryarcana.item.ItemMultiSWA.getItemStackDisplayName(ItemMultiSWA.java:55) ~[ItemMultiSWA.class:?]
	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:679) ~[aip.class:?]
	at net.minecraft.item.ItemStack.getTextComponent(ItemStack.java:1126) ~[aip.class:?]
	at net.minecraft.stats.StatList.initStats(StatList.java:581) ~[qs.class:?]
	at net.minecraft.stats.StatList.init(StatList.java:551) ~[qs.class:?]
	at net.minecraft.stats.StatList.reinit(StatList.java:694) ~[qs.class:?]
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:581) ~[Magma-1.12.2-3dc9bdb1.jar:1.12.2-3dc9bdb1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_333]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:894) ~[Loader.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259) ~[GameData.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733) ~[Loader.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112) ~[FMLServerHandler.class:1.12.2-3dc9bdb1]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:342) ~[FMLCommonHandler.class:1.12.2-3dc9bdb1]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:269) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:110) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_333]
	... 30 more

**Comment by Sereath** [comment]
Here to report the same, a server crash during initialization.

https://gist.github.com/Sereath/5fdad4883951c1ebd4c8d7797423da40

**Comment by VanyaBaou** [comment]
Fixed in newest ver https://github.com/VanyaBaou/SpartanWeaponryArcana/commit/35a5b2ed7399255b3b7535bbe39c31295b6f75b9
